configuration: Release

install:
- ps: |
    $env:CORE_SDK_VERSION = '5.0.100-preview.3.20216.6'
    Write-Host "Installing .NET Core SDK $env:CORE_SDK_VERSION"
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version $env:CORE_SDK_VERSION -InstallDir "$env:ProgramFiles\dotnet"

before_build:
- cd specs
- nuget restore

branches:
  only:
    - master

build:
  verbosity: minimal
  project: specs\LogoFX.Cli.Dotnet.Specs.sln

image: Visual Studio 2019
  
notifications:
- provider: Email
  to:
  - gennady.verdel@gmail.com
  - david@logoui.co.il
  - dmitry.bublik@logoui.co.il
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true